version: '3'
services:
    web:
        image: nginx
        volumes:
            - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./app:/app
        ports:
#            - 80:80
#           Use a diferent port - set in .env
            - ${WEB_PORT}:80
        restart: always
        depends_on:
            - php
    php:
        build: .docker
        restart: always
        volumes:
            - ./conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./app/:/app
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
    composer:
        image: composer
        volumes:
            - ./conf/composer:/app
        command: install --ignore-platform-reqs
    db:
        image: postgres
        restart: always
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
#            - 5432:5432
             - :5432
        volumes:
            - ./conf/postgres/:/docker-entrypoint-initdb.d/
